名字: Android CI

在:
推:
分支: [ "context" ]
query为空workflow_dispatch:

权限:
内容: 阅读
页: 写
  id-token: 写

工作:
建筑:
环境:
名字: github-pages
统一资源定位系统: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

步骤:
    - 用途: actions/checkout@v3
与:
子模块: 'recursive'
        fetch-depth: 0
    - 名字: 设置JDK 17
用途: actions/setup-java@v3
与:
        java-version: '17'
分布: 'temurin'
贮存物: gradle

    - 名字: 用梯级建造
跑: |
echo 'org.gradle.caching=true' >> gradle.properties
echo 'org.gradle.parallel=true' >> gradle.properties
echo 'org.gradle.vfs.watch=true' >> gradle.properties
echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
./gradlew publishToMavenLocal
停
env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}
    - 名字: 上传库
用途: actions/upload-artifact@v3
与:
名字: 图书馆
路径: ~/.m2
    - 名字: 上传网页
用途: actions/upload-pages-artifact@v1
与:
        #上传整个仓库
路径: 'api/build/intermediates/java_doc_dir/release'
    - 名字: 部署到GitHub页面
身份证: 部署
用途: actions/deploy-pages@main

